name: Python Lint and Style Check

on:
  pull_request:
    branches:
      - main
      - master
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort pylint

      - name: Run black check
        run: |
          black --check .

      - name: Run isort check
        run: |
          isort --check-only --diff .

      - name: Run flake8 lint
        run: |
          flake8 .

      - name: Run pylint
        run: |
          pylint .
