name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: pip install flake8 black isort mypy
      - name: Run Black
        run: black --check src tests
      - name: Run isort
        run: isort --check src tests
      - name: Run flake8
        run: flake8 src tests
      - name: Run mypy
        run: mypy src
